// Code generated by mockery v2.44.0. DO NOT EDIT.

package balance

import (
	context "context"

	model "github.com/ruslantos/gophemart-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// mockServiceGetWithdrawals is an autogenerated mock type for the serviceGetWithdrawals type
type mockServiceGetWithdrawals struct {
	mock.Mock
}

type mockServiceGetWithdrawals_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServiceGetWithdrawals) EXPECT() *mockServiceGetWithdrawals_Expecter {
	return &mockServiceGetWithdrawals_Expecter{mock: &_m.Mock}
}

// GetWithdrawalsByUserID provides a mock function with given fields: ctx, userID
func (_m *mockServiceGetWithdrawals) GetWithdrawalsByUserID(ctx context.Context, userID string) ([]model.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalsByUserID")
	}

	var r0 []model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawalsByUserID'
type mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call struct {
	*mock.Call
}

// GetWithdrawalsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockServiceGetWithdrawals_Expecter) GetWithdrawalsByUserID(ctx interface{}, userID interface{}) *mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call {
	return &mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call{Call: _e.mock.On("GetWithdrawalsByUserID", ctx, userID)}
}

func (_c *mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call) Run(run func(ctx context.Context, userID string)) *mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call) Return(_a0 []model.Withdrawal, _a1 error) *mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call) RunAndReturn(run func(context.Context, string) ([]model.Withdrawal, error)) *mockServiceGetWithdrawals_GetWithdrawalsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockServiceGetWithdrawals creates a new instance of mockServiceGetWithdrawals. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServiceGetWithdrawals(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServiceGetWithdrawals {
	mock := &mockServiceGetWithdrawals{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
