// Code generated by mockery v2.44.0. DO NOT EDIT.

package balance

import (
	context "context"

	model "github.com/ruslantos/gophemart-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// mockServiceWithdraw is an autogenerated mock type for the serviceWithdraw type
type mockServiceWithdraw struct {
	mock.Mock
}

type mockServiceWithdraw_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServiceWithdraw) EXPECT() *mockServiceWithdraw_Expecter {
	return &mockServiceWithdraw_Expecter{mock: &_m.Mock}
}

// Withdraw provides a mock function with given fields: ctx, withdrawal
func (_m *mockServiceWithdraw) Withdraw(ctx context.Context, withdrawal model.Withdrawal) error {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Withdrawal) error); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockServiceWithdraw_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type mockServiceWithdraw_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal model.Withdrawal
func (_e *mockServiceWithdraw_Expecter) Withdraw(ctx interface{}, withdrawal interface{}) *mockServiceWithdraw_Withdraw_Call {
	return &mockServiceWithdraw_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, withdrawal)}
}

func (_c *mockServiceWithdraw_Withdraw_Call) Run(run func(ctx context.Context, withdrawal model.Withdrawal)) *mockServiceWithdraw_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Withdrawal))
	})
	return _c
}

func (_c *mockServiceWithdraw_Withdraw_Call) Return(_a0 error) *mockServiceWithdraw_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockServiceWithdraw_Withdraw_Call) RunAndReturn(run func(context.Context, model.Withdrawal) error) *mockServiceWithdraw_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// newMockServiceWithdraw creates a new instance of mockServiceWithdraw. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServiceWithdraw(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServiceWithdraw {
	mock := &mockServiceWithdraw{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
