// Code generated by mockery v2.44.0. DO NOT EDIT.

package balance

import (
	context "context"

	model "github.com/ruslantos/gophemart-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// mockServiceGetBalance is an autogenerated mock type for the serviceGetBalance type
type mockServiceGetBalance struct {
	mock.Mock
}

type mockServiceGetBalance_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServiceGetBalance) EXPECT() *mockServiceGetBalance_Expecter {
	return &mockServiceGetBalance_Expecter{mock: &_m.Mock}
}

// GetUserBalance provides a mock function with given fields: ctx, userID
func (_m *mockServiceGetBalance) GetUserBalance(ctx context.Context, userID string) (model.UserBalance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 model.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.UserBalance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.UserBalance); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.UserBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServiceGetBalance_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type mockServiceGetBalance_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockServiceGetBalance_Expecter) GetUserBalance(ctx interface{}, userID interface{}) *mockServiceGetBalance_GetUserBalance_Call {
	return &mockServiceGetBalance_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, userID)}
}

func (_c *mockServiceGetBalance_GetUserBalance_Call) Run(run func(ctx context.Context, userID string)) *mockServiceGetBalance_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockServiceGetBalance_GetUserBalance_Call) Return(_a0 model.UserBalance, _a1 error) *mockServiceGetBalance_GetUserBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServiceGetBalance_GetUserBalance_Call) RunAndReturn(run func(context.Context, string) (model.UserBalance, error)) *mockServiceGetBalance_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// newMockServiceGetBalance creates a new instance of mockServiceGetBalance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServiceGetBalance(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServiceGetBalance {
	mock := &mockServiceGetBalance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
