// Code generated by mockery v2.44.0. DO NOT EDIT.

package register

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockService is an autogenerated mock type for the service type
type mockService struct {
	mock.Mock
}

type mockService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockService) EXPECT() *mockService_Expecter {
	return &mockService_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, login, password
func (_m *mockService) Register(ctx context.Context, login string, password string) error {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type mockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *mockService_Expecter) Register(ctx interface{}, login interface{}, password interface{}) *mockService_Register_Call {
	return &mockService_Register_Call{Call: _e.mock.On("Register", ctx, login, password)}
}

func (_c *mockService_Register_Call) Run(run func(ctx context.Context, login string, password string)) *mockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockService_Register_Call) Return(_a0 error) *mockService_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockService_Register_Call) RunAndReturn(run func(context.Context, string, string) error) *mockService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// newMockService creates a new instance of mockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockService {
	mock := &mockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
