// Code generated by mockery v2.50.0. DO NOT EDIT.

package postorders

import (
	context "context"

	model "github.com/ruslantos/gophemart-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Mockservice is an autogenerated mock type for the service type
type Mockservice struct {
	mock.Mock
}

type Mockservice_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockservice) EXPECT() *Mockservice_Expecter {
	return &Mockservice_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: ctx, orderNumber
func (_m *Mockservice) GetOrder(ctx context.Context, orderNumber string) (model.Order, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockservice_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type Mockservice_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *Mockservice_Expecter) GetOrder(ctx interface{}, orderNumber interface{}) *Mockservice_GetOrder_Call {
	return &Mockservice_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderNumber)}
}

func (_c *Mockservice_GetOrder_Call) Run(run func(ctx context.Context, orderNumber string)) *Mockservice_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Mockservice_GetOrder_Call) Return(_a0 model.Order, _a1 error) *Mockservice_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockservice_GetOrder_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *Mockservice_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function with given fields: ctx, order
func (_m *Mockservice) SaveOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockservice_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type Mockservice_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *Mockservice_Expecter) SaveOrder(ctx interface{}, order interface{}) *Mockservice_SaveOrder_Call {
	return &Mockservice_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order)}
}

func (_c *Mockservice_SaveOrder_Call) Run(run func(ctx context.Context, order model.Order)) *Mockservice_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *Mockservice_SaveOrder_Call) Return(_a0 error) *Mockservice_SaveOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_SaveOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *Mockservice_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SendOrderToLoyaltyClient provides a mock function with given fields: order
func (_m *Mockservice) SendOrderToLoyaltyClient(order model.Order) {
	_m.Called(order)
}

// Mockservice_SendOrderToLoyaltyClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderToLoyaltyClient'
type Mockservice_SendOrderToLoyaltyClient_Call struct {
	*mock.Call
}

// SendOrderToLoyaltyClient is a helper method to define mock.On call
//   - order model.Order
func (_e *Mockservice_Expecter) SendOrderToLoyaltyClient(order interface{}) *Mockservice_SendOrderToLoyaltyClient_Call {
	return &Mockservice_SendOrderToLoyaltyClient_Call{Call: _e.mock.On("SendOrderToLoyaltyClient", order)}
}

func (_c *Mockservice_SendOrderToLoyaltyClient_Call) Run(run func(order model.Order)) *Mockservice_SendOrderToLoyaltyClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Order))
	})
	return _c
}

func (_c *Mockservice_SendOrderToLoyaltyClient_Call) Return() *Mockservice_SendOrderToLoyaltyClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mockservice_SendOrderToLoyaltyClient_Call) RunAndReturn(run func(model.Order)) *Mockservice_SendOrderToLoyaltyClient_Call {
	_c.Run(run)
	return _c
}

// NewMockservice creates a new instance of Mockservice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockservice(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockservice {
	mock := &Mockservice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
