// Code generated by mockery v2.44.0. DO NOT EDIT.

package service

import (
	context "context"

	clients "github.com/ruslantos/gophemart-service/internal/clients"

	mock "github.com/stretchr/testify/mock"
)

// mockClient is an autogenerated mock type for the client type
type mockClient struct {
	mock.Mock
}

type mockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockClient) EXPECT() *mockClient_Expecter {
	return &mockClient_Expecter{mock: &_m.Mock}
}

// GetOrderInfo provides a mock function with given fields: ctx, orderNumber
func (_m *mockClient) GetOrderInfo(ctx context.Context, orderNumber string) (*clients.OrderResponse, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderInfo")
	}

	var r0 *clients.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*clients.OrderResponse, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *clients.OrderResponse); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockClient_GetOrderInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderInfo'
type mockClient_GetOrderInfo_Call struct {
	*mock.Call
}

// GetOrderInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *mockClient_Expecter) GetOrderInfo(ctx interface{}, orderNumber interface{}) *mockClient_GetOrderInfo_Call {
	return &mockClient_GetOrderInfo_Call{Call: _e.mock.On("GetOrderInfo", ctx, orderNumber)}
}

func (_c *mockClient_GetOrderInfo_Call) Run(run func(ctx context.Context, orderNumber string)) *mockClient_GetOrderInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockClient_GetOrderInfo_Call) Return(_a0 *clients.OrderResponse, _a1 error) *mockClient_GetOrderInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockClient_GetOrderInfo_Call) RunAndReturn(run func(context.Context, string) (*clients.OrderResponse, error)) *mockClient_GetOrderInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockClient creates a new instance of mockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockClient {
	mock := &mockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
