// Code generated by mockery v2.44.0. DO NOT EDIT.

package service

import (
	context "context"

	model "github.com/ruslantos/gophemart-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// mockRepo is an autogenerated mock type for the repo type
type mockRepo struct {
	mock.Mock
}

type mockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRepo) EXPECT() *mockRepo_Expecter {
	return &mockRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, login, password
func (_m *mockRepo) CreateUser(ctx context.Context, login string, password string) error {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *mockRepo_Expecter) CreateUser(ctx interface{}, login interface{}, password interface{}) *mockRepo_CreateUser_Call {
	return &mockRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, login, password)}
}

func (_c *mockRepo_CreateUser_Call) Run(run func(ctx context.Context, login string, password string)) *mockRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockRepo_CreateUser_Call) Return(_a0 error) *mockRepo_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRepo_CreateUser_Call) RunAndReturn(run func(context.Context, string, string) error) *mockRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, orderID
func (_m *mockRepo) GetOrder(ctx context.Context, orderID string) (model.Order, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRepo_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type mockRepo_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *mockRepo_Expecter) GetOrder(ctx interface{}, orderID interface{}) *mockRepo_GetOrder_Call {
	return &mockRepo_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderID)}
}

func (_c *mockRepo_GetOrder_Call) Run(run func(ctx context.Context, orderID string)) *mockRepo_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockRepo_GetOrder_Call) Return(_a0 model.Order, _a1 error) *mockRepo_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRepo_GetOrder_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *mockRepo_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function with given fields: ctx, userID
func (_m *mockRepo) GetOrders(ctx context.Context, userID string) ([]model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRepo_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type mockRepo_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockRepo_Expecter) GetOrders(ctx interface{}, userID interface{}) *mockRepo_GetOrders_Call {
	return &mockRepo_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx, userID)}
}

func (_c *mockRepo_GetOrders_Call) Run(run func(ctx context.Context, userID string)) *mockRepo_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockRepo_GetOrders_Call) Return(_a0 []model.Order, _a1 error) *mockRepo_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRepo_GetOrders_Call) RunAndReturn(run func(context.Context, string) ([]model.Order, error)) *mockRepo_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersByStates provides a mock function with given fields: ctx, states
func (_m *mockRepo) GetOrdersByStates(ctx context.Context, states []string) ([]model.Order, error) {
	ret := _m.Called(ctx, states)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByStates")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]model.Order, error)); ok {
		return rf(ctx, states)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []model.Order); ok {
		r0 = rf(ctx, states)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, states)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRepo_GetOrdersByStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByStates'
type mockRepo_GetOrdersByStates_Call struct {
	*mock.Call
}

// GetOrdersByStates is a helper method to define mock.On call
//   - ctx context.Context
//   - states []string
func (_e *mockRepo_Expecter) GetOrdersByStates(ctx interface{}, states interface{}) *mockRepo_GetOrdersByStates_Call {
	return &mockRepo_GetOrdersByStates_Call{Call: _e.mock.On("GetOrdersByStates", ctx, states)}
}

func (_c *mockRepo_GetOrdersByStates_Call) Run(run func(ctx context.Context, states []string)) *mockRepo_GetOrdersByStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *mockRepo_GetOrdersByStates_Call) Return(_a0 []model.Order, _a1 error) *mockRepo_GetOrdersByStates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRepo_GetOrdersByStates_Call) RunAndReturn(run func(context.Context, []string) ([]model.Order, error)) *mockRepo_GetOrdersByStates_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAccrualSum provides a mock function with given fields: ctx, userID
func (_m *mockRepo) GetUserAccrualSum(ctx context.Context, userID string) (model.UserBalance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAccrualSum")
	}

	var r0 model.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.UserBalance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.UserBalance); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.UserBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRepo_GetUserAccrualSum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAccrualSum'
type mockRepo_GetUserAccrualSum_Call struct {
	*mock.Call
}

// GetUserAccrualSum is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockRepo_Expecter) GetUserAccrualSum(ctx interface{}, userID interface{}) *mockRepo_GetUserAccrualSum_Call {
	return &mockRepo_GetUserAccrualSum_Call{Call: _e.mock.On("GetUserAccrualSum", ctx, userID)}
}

func (_c *mockRepo_GetUserAccrualSum_Call) Run(run func(ctx context.Context, userID string)) *mockRepo_GetUserAccrualSum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockRepo_GetUserAccrualSum_Call) Return(_a0 model.UserBalance, _a1 error) *mockRepo_GetUserAccrualSum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRepo_GetUserAccrualSum_Call) RunAndReturn(run func(context.Context, string) (model.UserBalance, error)) *mockRepo_GetUserAccrualSum_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function with given fields: ctx, login
func (_m *mockRepo) GetUserByLogin(ctx context.Context, login string) (*model.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRepo_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type mockRepo_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *mockRepo_Expecter) GetUserByLogin(ctx interface{}, login interface{}) *mockRepo_GetUserByLogin_Call {
	return &mockRepo_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *mockRepo_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *mockRepo_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockRepo_GetUserByLogin_Call) Return(_a0 *model.User, _a1 error) *mockRepo_GetUserByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRepo_GetUserByLogin_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *mockRepo_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawalsByUserID provides a mock function with given fields: ctx, userID
func (_m *mockRepo) GetWithdrawalsByUserID(ctx context.Context, userID string) ([]model.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalsByUserID")
	}

	var r0 []model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRepo_GetWithdrawalsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawalsByUserID'
type mockRepo_GetWithdrawalsByUserID_Call struct {
	*mock.Call
}

// GetWithdrawalsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockRepo_Expecter) GetWithdrawalsByUserID(ctx interface{}, userID interface{}) *mockRepo_GetWithdrawalsByUserID_Call {
	return &mockRepo_GetWithdrawalsByUserID_Call{Call: _e.mock.On("GetWithdrawalsByUserID", ctx, userID)}
}

func (_c *mockRepo_GetWithdrawalsByUserID_Call) Run(run func(ctx context.Context, userID string)) *mockRepo_GetWithdrawalsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockRepo_GetWithdrawalsByUserID_Call) Return(_a0 []model.Withdrawal, _a1 error) *mockRepo_GetWithdrawalsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRepo_GetWithdrawalsByUserID_Call) RunAndReturn(run func(context.Context, string) ([]model.Withdrawal, error)) *mockRepo_GetWithdrawalsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function with given fields: ctx, order
func (_m *mockRepo) SaveOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRepo_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type mockRepo_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *mockRepo_Expecter) SaveOrder(ctx interface{}, order interface{}) *mockRepo_SaveOrder_Call {
	return &mockRepo_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order)}
}

func (_c *mockRepo_SaveOrder_Call) Run(run func(ctx context.Context, order model.Order)) *mockRepo_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *mockRepo_SaveOrder_Call) Return(_a0 error) *mockRepo_SaveOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRepo_SaveOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *mockRepo_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserAccrualSum provides a mock function with given fields: ctx, order
func (_m *mockRepo) UpdateUserAccrualSum(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserAccrualSum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRepo_UpdateUserAccrualSum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserAccrualSum'
type mockRepo_UpdateUserAccrualSum_Call struct {
	*mock.Call
}

// UpdateUserAccrualSum is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *mockRepo_Expecter) UpdateUserAccrualSum(ctx interface{}, order interface{}) *mockRepo_UpdateUserAccrualSum_Call {
	return &mockRepo_UpdateUserAccrualSum_Call{Call: _e.mock.On("UpdateUserAccrualSum", ctx, order)}
}

func (_c *mockRepo_UpdateUserAccrualSum_Call) Run(run func(ctx context.Context, order model.Order)) *mockRepo_UpdateUserAccrualSum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *mockRepo_UpdateUserAccrualSum_Call) Return(_a0 error) *mockRepo_UpdateUserAccrualSum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRepo_UpdateUserAccrualSum_Call) RunAndReturn(run func(context.Context, model.Order) error) *mockRepo_UpdateUserAccrualSum_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, withdrawal
func (_m *mockRepo) Withdraw(ctx context.Context, withdrawal model.Withdrawal) error {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Withdrawal) error); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRepo_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type mockRepo_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal model.Withdrawal
func (_e *mockRepo_Expecter) Withdraw(ctx interface{}, withdrawal interface{}) *mockRepo_Withdraw_Call {
	return &mockRepo_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, withdrawal)}
}

func (_c *mockRepo_Withdraw_Call) Run(run func(ctx context.Context, withdrawal model.Withdrawal)) *mockRepo_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Withdrawal))
	})
	return _c
}

func (_c *mockRepo_Withdraw_Call) Return(_a0 error) *mockRepo_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRepo_Withdraw_Call) RunAndReturn(run func(context.Context, model.Withdrawal) error) *mockRepo_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRepo creates a new instance of mockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRepo {
	mock := &mockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
