// Code generated by mockery v2.50.0. DO NOT EDIT.

package handler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockservice is an autogenerated mock type for the service type
type Mockservice struct {
	mock.Mock
}

type Mockservice_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockservice) EXPECT() *Mockservice_Expecter {
	return &Mockservice_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, login, password
func (_m *Mockservice) Authenticate(ctx context.Context, login string, password string) bool {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Mockservice_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type Mockservice_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *Mockservice_Expecter) Authenticate(ctx interface{}, login interface{}, password interface{}) *Mockservice_Authenticate_Call {
	return &Mockservice_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, login, password)}
}

func (_c *Mockservice_Authenticate_Call) Run(run func(ctx context.Context, login string, password string)) *Mockservice_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Mockservice_Authenticate_Call) Return(_a0 bool) *Mockservice_Authenticate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockservice_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) bool) *Mockservice_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockservice creates a new instance of Mockservice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockservice(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockservice {
	mock := &Mockservice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
