// Code generated by mockery v2.44.0. DO NOT EDIT.

package orders

import (
	context "context"

	model "github.com/ruslantos/gophemart-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// mockServicePost is an autogenerated mock type for the servicePost type
type mockServicePost struct {
	mock.Mock
}

type mockServicePost_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServicePost) EXPECT() *mockServicePost_Expecter {
	return &mockServicePost_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: ctx, orderNumber
func (_m *mockServicePost) GetOrder(ctx context.Context, orderNumber string) (model.Order, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServicePost_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type mockServicePost_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *mockServicePost_Expecter) GetOrder(ctx interface{}, orderNumber interface{}) *mockServicePost_GetOrder_Call {
	return &mockServicePost_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderNumber)}
}

func (_c *mockServicePost_GetOrder_Call) Run(run func(ctx context.Context, orderNumber string)) *mockServicePost_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockServicePost_GetOrder_Call) Return(_a0 model.Order, _a1 error) *mockServicePost_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServicePost_GetOrder_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *mockServicePost_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function with given fields: ctx, order
func (_m *mockServicePost) SaveOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockServicePost_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type mockServicePost_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *mockServicePost_Expecter) SaveOrder(ctx interface{}, order interface{}) *mockServicePost_SaveOrder_Call {
	return &mockServicePost_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order)}
}

func (_c *mockServicePost_SaveOrder_Call) Run(run func(ctx context.Context, order model.Order)) *mockServicePost_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *mockServicePost_SaveOrder_Call) Return(_a0 error) *mockServicePost_SaveOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockServicePost_SaveOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *mockServicePost_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// newMockServicePost creates a new instance of mockServicePost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServicePost(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServicePost {
	mock := &mockServicePost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
